<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP782OSr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP782OSr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP782OSr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP782OSr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerP782OSr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'P782OSr',
    'container.build_id' => 'c22b959c',
    'container.build_time' => 1566052586,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP782OSr');
